### https://www.kaggle.com/competitions/drawing-with-llms

In [1]:
import kagglehub
import pandas as pd

In [2]:
from unsloth import FastLanguageModel
import torch

dtype = ( None )
load_in_4bit = False
load_in_8bit = False
#unsloth/Llama-3.2-3B-Instruct
#Qwen/Qwen2.5-Coder-3B
#Qwen/Qwen2.5-Coder-7B-Instruct
#Qwen/Qwen2.5-14B-Instruct

######---Parameters to change---#######
base_model="Llama-3.2-3B-Instruct"      
max_seq_length = 2048
Rank=256
sample_len=2000
max_iter_steps=500
###--------------------------------###

train_parameters=f"_lora_fp16_r{Rank}_s{sample_len}_i{max_iter_steps}_msl{max_seq_length}"

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/"+base_model,
    #model_name= "./lora/Qwen25_7B_Instruct_lora_fp16_r256_s2000_i2000_msl2048",
    max_seq_length=max_seq_length,
    dtype=dtype,
    load_in_4bit=load_in_4bit,
    load_in_8bit=load_in_8bit
)

print(model.dtype)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
INFO 04-26 16:48:11 [__init__.py:239] Automatically detected platform cuda.
==((====))==  Unsloth 2025.3.18: Fast Llama patching. Transformers: 4.47.1. vLLM: 0.8.2.
   \\   /|    NVIDIA GeForce RTX 4070 Ti SUPER. Num GPUs = 1. Max memory: 15.693 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.6.0+cu124. CUDA: 8.9. CUDA Toolkit: 12.4. Triton: 3.2.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.29.post2. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
torch.bfloat16

In [3]:
model

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(128256, 3072, padding_idx=128004)
    (layers): ModuleList(
      (0-27): 28 x LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=3072, out_features=3072, bias=False)
          (k_proj): Linear(in_features=3072, out_features=1024, bias=False)
          (v_proj): Linear(in_features=3072, out_features=1024, bias=False)
          (o_proj): Linear(in_features=3072, out_features=3072, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=3072, out_features=8192, bias=False)
          (up_proj): Linear(in_features=3072, out_features=8192, bias=False)
          (down_proj): Linear(in_features=8192, out_features=3072, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm((3072,), eps=1e-05)
        (post_attention_layernorm): LlamaRMSNorm((3072,), eps=1e-05)
      )
    )
    (norm): LlamaRMSNorm((3072,), eps=1e-05)
    (rotary_emb): LlamaRotaryEmbedding()
  )
  (lm_head): Linear(in_features=3072, out_features=128256, bias=False)
)

In [4]:
model = FastLanguageModel.get_peft_model(
    model,
    r = Rank, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
    random_state = 123,
    use_rslora = False,  # We support rank stabilized LoRA
    loftq_config = None, # And LoftQ
)

Unsloth 2025.3.18 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.

In [5]:
df_train=pd.read_csv('./drawing-with-llms/svg_score_extend_train1.csv')
df_train.head(2)

,description,response_1,gpt_svg_1,gpt_score_1
0,"'Golden wheat fields under a setting sun',","```svg\n<svg viewBox=""0 0 200 200"" width=""200""...","<svg viewBox=""0 0 200 200"" width=""200"" height=...",0.994973
1,"'Snowy mountains under a clear blue sky',","```svg\n<svg viewBox=""0 0 200 100"" width=""200""...","<svg viewBox=""0 0 200 100"" width=""200"" height=...",0.978844

In [6]:
df_test=pd.read_csv('./drawing-with-llms/svg_score_test_vqa.csv')
df_test.head(2)

,description,gpt_svg_1,gpt_score_sl,response,vqa_pair,response_2,gpt_svg_2
0,"'Vibrant autumn forest',","<svg viewBox=""0 0 200 200"" width=""200"" height=...",0.904117,Here is the visual question answering (VQA) pa...,"{'description': 'Vibrant autumn forest', 'ques...","Here's an improved SVG representation of a ""Vi...","<svg xmlns=""http://www.w3.org/2000/svg"" viewBo..."
1,"'Morning dew on grass',","<svg viewBox=""0 0 200 200"" width=""200"" height=...",0.987024,Here is a visual question answering (VQA) pair...,"{'description': 'Morning dew on grass', 'quest...","Here's an improved SVG representation of ""Morn...","<svg xmlns=""http://www.w3.org/2000/svg"" viewBo..."

In [7]:
alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{}

### Input:
{}

### Response:
{}
"""

EOS_TOKEN = tokenizer.eos_token  # Must add EOS_TOKEN

def formatting_prompts_func(examples):
    topics = examples["description"]  # Using 'topic' as instruction
    svgs = examples["gpt_svg_1"]  # Using 'svg_code' as output
    texts = []

    
    for topic, svg_code in zip(topics, svgs):
        # No additional input is needed, so we pass an empty string
        text = alpaca_prompt.format(f"Generate a SVG code for the given input:",topic,svg_code) + EOS_TOKEN
        texts.append(text)

        print(texts)
        
    return { "text": texts }

from datasets import Dataset
import pandas as pd
# Convert DataFrame to Hugging Face Dataset
dataset_train = Dataset.from_pandas(df_train)
dataset_train = dataset_train.map(formatting_prompts_func, batched=True)

dataset_test = Dataset.from_pandas(df_test)
dataset_test = dataset_test.map(formatting_prompts_func, batched=True)

Map:   0%|          | 0/1975 [00:00<?, ? examples/s]

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

Map:   0%|          | 0/75 [00:00<?, ? examples/s]

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

['Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nGenerate a SVG code for the given input:\n\n### Input:\n \'Vibrant autumn forest\',\n\n### Response:\n<svg viewBox="0 0 200 200" width="200" height="200" xmlns="http://www.w3.org/2000/svg">\n  <defs>\n    <linearGradient id="autumnGradient" x1="0" y1="0" x2="1" y2="1">\n      <stop offset="0%" stop-color="#FF7F50" />\n      <stop offset="50%" stop-color="#FFD700" />\n      <stop offset="100%" stop-color="#8B4513" />\n    </linearGradient>\n  </defs>\n  <rect x="0" y="0" width="200" height="200" fill="url(#autumnGradient)" />\n  <g transform="translate(50, 150)">\n    <rect x="-10" y="-60" width="20" height="60" fill="#8B4513" />\n    <circle cx="0" cy="-80" r="30" fill="#FF4500" />\n    <circle cx="-25" cy="-100" r="20" fill="#FFD700" />\n    <circle cx="25" cy="-100" r="20" fill="#FF6347" />\n  </g>\n  <g transform="translate(150, 150)">\n    <rect x="-10" y="-60" width="20" height="60" fill="#8B4513" />\n    <circle cx="0" cy="-80" r="30" fill="#FF4500" />\n    <circle cx="-25" cy="-100" r="20" fill="#FFD700" />\n    <circle cx="25" cy="-100" r="20" fill="#FF6347" />\n  </g>\n  <g transform="translate(100, 150)">\n    <rect x="-10" y="-60" width="20" height="60" fill="#8B4513" />\n    <circle cx="0" cy="-80" r="30" fill="#FF4500" />\n    <circle cx="-25" cy="-100" r="20" fill="#FFD700" />\n    <circle cx="25" cy="-100" r="20" fill="#FF6347" />\n  </g>\n</svg>\n<|eot_id|>', 'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nGenerate a SVG code for the given input:\n\n### Input:\n \'Morning dew on grass\',\n\n### Response:\n<svg viewBox="0 0 200 200" width="200" height="200" xmlns="http://www.w3.org/2000/svg">\n  <!-- Background to represent morning sky -->\n  <rect x="0" y="0" width="200" height="200" fill="lightblue" />\n\n  <!-- Grass representation -->\n  <g fill="green" stroke="none">\n    <polygon points="0,150 200,150 200,200 0,200" />\n    <line x1="50" y1="150" x2="55" y2="130" stroke="green" stroke-width="2" />\n    <line x1="70" y1="150" x2="75" y2="120" stroke="green" stroke-width="2" />\n    <line x1="90" y1="150" x2="95" y2="135" stroke="green" stroke-width="2" />\n    <line x1="110" y1="150" x2="115" y2="125" stroke="green" stroke-width="2" />\n    <line x1="130" y1="150" x2="135" y2="140" stroke="green" stroke-width="2" />\n    <line x1="150" y1="150" x2="155" y2="130" stroke="green" stroke-width="2" />\n  </g>\n\n  <!-- Dew drops on grass -->\n  <g fill="lightblue" stroke="none">\n    <circle cx="55" cy="128" r="3" />\n    <circle cx="75" cy="118" r="3" />\n    <circle cx="95" cy="133" r="3" />\n    <circle cx="115" cy="123" r="3" />\n    <circle cx="135" cy="138" r="3" />\n    <circle cx="155" cy="128" r="3" />\n  </g>\n</svg>\n<|eot_id|>', 'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nGenerate a SVG code for the given input:\n\n### Input:\n \'Warm desert sunset\',\n\n### Response:\n<svg viewBox="0 0 200 200" width="200" height="200" xmlns="http://www.w3.org/2000/svg">\n  <!-- Background -->\n  <rect x="0" y="0" width="200" height="200" fill="orange" />\n\n  <!-- Sun -->\n  <circle cx="100" cy="60" r="30" fill="yellow" />\n\n  <!-- Sand Dunes -->\n  <path d="M0 150 Q50 120 100 150 T200 150 L200 200 L0 200 Z" fill="sandybrown" />\n\n  <!-- Distant Dunes -->\n  <path d="M0 130 Q50 100 100 130 T200 130 L200 200 L0 200 Z" fill="peru" opacity="0.7" />\n\n  <!-- Sky Gradient -->\n  <defs>\n    <linearGradient id="skyGradient" x1="0" y1="0" x2="0" y2="1">\n      <stop offset="0%" stop-color="lightcoral" />\n      <stop offset="100%" stop-color="orange" />\n    </linearGradient>\n  </defs>\n  <rect x="0" y="0" width="200" height="100" fill="url(#skyGradient)" />\n</svg>\n<|eot_id|>', 'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nGenerate a SVG code for the given input:\n\n### Input:\n \'Tropical beach scene\',\n\n### Response:\n<svg viewBox="0 0 200 200" width="200" height="200" xmlns="http://www.w3.org/2000/svg">\n  <!-- Sky -->\n  <rect x="0" y="0" width="200" height="100" fill="skyblue" />\n  <!-- Ocean -->\n  <rect x="0" y="100" width="200" height="50" fill="deepskyblue" />\n  <!-- Sand -->\n  <rect x="0" y="150" width="200" height="50" fill="sandybrown" />\n  <!-- Sun -->\n  <circle cx="160" cy="40" r="20" fill="yellow" />\n  <!-- Palm Tree Trunk -->\n  <rect x="50" y="90" width="10" height="60" fill="saddlebrown" />\n  <!-- Palm Tree Leaves -->\n  <polygon points="55,90 35,70 75,70" fill="green" />\n  <polygon points="55,90 40,60 70,60" fill="green" />\n  <polygon points="55,90 45,50 65,50" fill="green" />\n</svg>\n<|eot_id|>', 'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nGenerate a SVG code for the given input:\n\n### Input:\n \'Futuristic cityscape\',\n\n### Response:\n<svg viewBox="0 0 200 200" width="200" height="200" xmlns="http://www.w3.org/2000/svg">\n  <!-- Background -->\n  <rect x="0" y="0" width="200" height="200" fill="black" />\n\n  <!-- Buildings -->\n  <rect x="20" y="80" width="30" height="120" fill="gray" />\n  <rect x="60" y="50" width="40" height="150" fill="darkgray" />\n  <rect x="110" y="70" width="30" height="130" fill="lightgray" />\n  <rect x="150" y="60" width="30" height="140" fill="dimgray" />\n\n  <!-- Windows -->\n  <g fill="yellow">\n    <!-- Building 1 -->\n    <rect x="25" y="90" width="5" height="5" />\n    <rect x="35" y="90" width="5" height="5" />\n    <rect x="25" y="100" width="5" height="5" />\n    <rect x="35" y="100" width="5" height="5" />\n\n    <!-- Building 2 -->\n    <rect x="65" y="60" width="5" height="5" />\n    <rect x="75" y="60" width="5" height="5" />\n    <rect x="85" y="60" width="5" height="5" />\n    <rect x="65" y="70" width="5" height="5" />\n    <rect x="75" y="70" width="5" height="5" />\n    <rect x="85" y="70" width="5" height="5" />\n\n    <!-- Building 3 -->\n    <rect x="115" y="80" width="5" height="5" />\n    <rect x="125" y="80" width="5" height="5" />\n    <rect x="115" y="90" width="5" height="5" />\n    <rect x="125" y="90" width="5" height="5" />\n\n    <!-- Building 4 -->\n    <rect x="155" y="70" width="5" height="5" />\n    <rect x="165" y="70" width="5" height="5" />\n    <rect x="155" y="80" width="5" height="5" />\n    <rect x="165" y="80" width="5" height="5" />\n  </g>\n\n  <!-- Sky elements -->\n  <circle cx="50" cy="30" r="10" fill="white" opacity="0.5" />\n  <circle cx="150" cy="20" r="15" fill="white" opacity="0.3" />\n\n  <!-- Futuristic elements -->\n  <line x1="0" y1="150" x2="200" y2="150" stroke="cyan" stroke-width="2" />\n  <polyline points="0,180 50,160 100,180 150,160 200,180" fill="none" stroke="cyan" stroke-width="2" />\n</svg>\n<|eot_id|>', 'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nGenerate a SVG code for the given input:\n\n### Input:\n \'Bold stripes and polka dots\',\n\n### Response:\n<svg viewBox="0 0 200 200" width="200" height="200" xmlns="http://www.w3.org/2000/svg">\n  <!-- Background with bold stripes -->\n  <defs>\n    <linearGradient id="stripes" x1="0" y1="0" x2="1" y2="0">\n      <stop offset="0%" stop-color="black" />\n      <stop offset="50%" stop-color="black" />\n      <stop offset="50%" stop-color="white" />\n      <stop offset="100%" stop-color="white" />\n    </linearGradient>\n  </defs>\n  <rect x="0" y="0" width="200" height="200" fill="url(#stripes)" />\n\n  <!-- Polka dots -->\n  <g fill="red" opacity="0.7">\n    <circle cx="30" cy="30" r="10" />\n    <circle cx="70" cy="30" r="10" />\n    <circle cx="110" cy="30" r="10" />\n    <circle cx="150" cy="30" r="10" />\n    <circle cx="190" cy="30" r="10" />\n    \n    <circle cx="30" cy="70" r="10" />\n    <circle cx="70" cy="70" r="10" />\n    <circle cx="110" cy="70" r="10" />\n    <circle cx="150" cy="70" r="10" />\n    <circle cx="190" cy="70" r="10" />\n    \n    <circle cx="30" cy="110" r="10" />\n    <circle cx="70" cy="110" r="10" />\n    <circle cx="110" cy="110" r="10" />\n    <circle cx="150" cy="110" r="10" />\n    <circle cx="190" cy="110" r="10" />\n    \n    <circle cx="30" cy="150" r="10" />\n    <circle cx="70" cy="150" r="10" />\n    <circle cx="110" cy="150" r="10" />\n    <circle cx="150" cy="150" r="10" />\n    <circle cx="190" cy="150" r="10" />\n    \n    <circle cx="30" cy="190" r="10" />\n    <circle cx="70" cy="190" r="10" />\n    <circle cx="110" cy="190" r="10" />\n    <circle cx="150" cy="190" r="10" />\n    <circle cx="190" cy="190" r="10" />\n  </g>\n</svg>\n<|eot_id|>', 'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nGenerate a SVG code for the given input:\n\n### Input:\n \'Tranquil ocean waves\',\n\n### Response:\n<svg viewBox="0 0 200 100" width="200" height="100" xmlns="http://www.w3.org/2000/svg">\n  <defs>\n    <linearGradient id="oceanGradient" x1="0" y1="0" x2="0" y2="1">\n      <stop offset="0%" stop-color="#00c6ff" />\n      <stop offset="100%" stop-color="#0072ff" />\n    </linearGradient>\n  </defs>\n  <rect x="0" y="0" width="200" height="100" fill="url(#oceanGradient)" />\n  <path d="M0,60 Q20,50 40,60 T80,60 T120,60 T160,60 T200,60 L200,100 L0,100 Z" fill="#ffffff" opacity="0.5" />\n  <path d="M0,70 Q20,60 40,70 T80,70 T120,70 T160,70 T200,70 L200,100 L0,100 Z" fill="#ffffff" opacity="0.5" />\n  <path d="M0,80 Q20,70 40,80 T80,80 T120,80 T160,80 T200,80 L200,100 L0,100 Z" fill="#ffffff" opacity="0.5" />\n</svg>\n<|eot_id|>', 'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nGenerate a SVG code for the given input:\n\n### Input:\n \'Sunset over rolling hills\',\n\n### Response:\n<svg viewBox="0 0 200 100" width="200" height="100" xmlns="http://www.w3.org/2000/svg">\n  <!-- Sky -->\n  <rect x="0" y="0" width="200" height="100" fill="lightblue" />\n  \n  <!-- Sun -->\n  <circle cx="150" cy="30" r="15" fill="orange" />\n  \n  <!-- Hills -->\n  <path d="M0 70 Q50 50 100 70 T200 70 L200 100 L0 100 Z" fill="green" />\n  \n  <!-- Sunset Gradient -->\n  <defs>\n    <linearGradient id="sunsetGradient" x1="0" y1="0" x2="0" y2="1">\n      <stop offset="0%" stop-color="orange" />\n      <stop offset="100%" stop-color="purple" />\n    </linearGradient>\n  </defs>\n  <rect x="0" y="0" width="200" height="100" fill="url(#sunsetGradient)" opacity="0.5" />\n</svg>\n<|eot_id|>', 'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nGenerate a SVG code for the given input:\n\n### Input:\n \'Abstract geometric shapes\',\n\n### Response:\n<svg viewBox="0 0 200 200" width="200" height="200" xmlns="http://www.w3.org/2000/svg">\n  <defs>\n    <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="0%">\n      <stop offset="0%" style="stop-color:rgb(255,255,0);stop-opacity:1" />\n      <stop offset="100%" style="stop-color:rgb(255,0,0);stop-opacity:1" />\n    </linearGradient>\n    <radialGradient id="grad2" cx="50%" cy="50%" r="50%" fx="50%" fy="50%">\n      <stop offset="0%" style="stop-color:rgb(0,255,255);stop-opacity:1" />\n      <stop offset="100%" style="stop-color:rgb(0,0,255);stop-opacity:1" />\n    </radialGradient>\n  </defs>\n  <rect x="10" y="10" width="50" height="50" fill="url(#grad1)" stroke="black" stroke-width="2" />\n  <circle cx="100" cy="50" r="25" fill="url(#grad2)" stroke="black" stroke-width="2" />\n  <ellipse cx="150" cy="50" rx="30" ry="15" fill="green" stroke="black" stroke-width="2" />\n  <line x1="10" y1="100" x2="190" y2="100" stroke="blue" stroke-width="2" />\n  <polyline points="10,120 40,150 70,120 100,150 130,120" fill="none" stroke="purple" stroke-width="2" />\n  <polygon points="150,120 170,150 190,120" fill="orange" stroke="black" stroke-width="2" />\n</svg>\n<|eot_id|>', 'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nGenerate a SVG code for the given input:\n\n### Input:\n \'Cloudy sky above the ocean\',\n\n### Response:\n<svg viewBox="0 0 200 100" width="200" height="100" xmlns="http://www.w3.org/2000/svg">\n  <!-- Ocean -->\n  <rect x="0" y="50" width="200" height="50" fill="lightblue" />\n\n  <!-- Clouds -->\n  <g fill="lightgray" stroke="none">\n    <ellipse cx="50" cy="30" rx="20" ry="10" />\n    <ellipse cx="70" cy="30" rx="20" ry="10" />\n    <ellipse cx="60" cy="25" rx="25" ry="15" />\n\n    <ellipse cx="130" cy="40" rx="20" ry="10" />\n    <ellipse cx="150" cy="40" rx="20" ry="10" />\n    <ellipse cx="140" cy="35" rx="25" ry="15" />\n  </g>\n</svg>\n<|eot_id|>', 'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nGenerate a SVG code for the given input:\n\n### Input:\n \'Quiet forest pathway\',\n\n### Response:\n<svg viewBox="0 0 200 200" width="200" height="200" xmlns="http://www.w3.org/2000/svg">\n  <!-- Background -->\n  <rect x="0" y="0" width="200" height="200" fill="lightgreen" />\n  \n  <!-- Pathway -->\n  <path d="M50,150 Q100,100 150,150" fill="none" stroke="saddlebrown" stroke-width="5" />\n\n  <!-- Trees -->\n  <g>\n    <!-- Tree 1 -->\n    <rect x="30" y="120" width="10" height="30" fill="sienna" />\n    <circle cx="35" cy="110" r="15" fill="forestgreen" />\n    \n    <!-- Tree 2 -->\n    <rect x="70" y="110" width="10" height="40" fill="sienna" />\n    <circle cx="75" cy="100" r="20" fill="forestgreen" />\n\n    <!-- Tree 3 -->\n    <rect x="130" y="130" width="10" height="20" fill="sienna" />\n    <circle cx="135" cy="120" r="15" fill="forestgreen" />\n\n    <!-- Tree 4 -->\n    <rect x="170" y="110" width="10" height="40" fill="sienna" />\n    <circle cx="175" cy="100" r="20" fill="forestgreen" />\n  </g>\n</svg>\n<|eot_id|>', 'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nGenerate a SVG code for the given input:\n\n### Input:\n \'Modern city skyline at night\',\n\n### Response:\n<svg viewBox="0 0 200 100" width="200" height="100" xmlns="http://www.w3.org/2000/svg">\n  <!-- Background for night sky -->\n  <rect x="0" y="0" width="200" height="100" fill="darkblue" />\n  \n  <!-- Moon -->\n  <circle cx="160" cy="20" r="10" fill="lightyellow" />\n\n  <!-- Buildings -->\n  <rect x="10" y="40" width="20" height="60" fill="gray" />\n  <rect x="40" y="30" width="20" height="70" fill="dimgray" />\n  <rect x="70" y="50" width="20" height="50" fill="darkgray" />\n  <rect x="100" y="20" width="20" height="80" fill="gray" />\n  <rect x="130" y="60" width="20" height="40" fill="dimgray" />\n  <rect x="160" y="35" width="20" height="65" fill="darkgray" />\n\n  <!-- Windows -->\n  <rect x="12" y="45" width="3" height="3" fill="yellow" />\n  <rect x="17" y="55" width="3" height="3" fill="yellow" />\n  <rect x="45" y="35" width="3" height="3" fill="yellow" />\n  <rect x="50" y="45" width="3" height="3" fill="yellow" />\n  <rect x="75" y="55" width="3" height="3" fill="yellow" />\n  <rect x="105" y="25" width="3" height="3" fill="yellow" />\n  <rect x="110" y="35" width="3" height="3" fill="yellow" />\n  <rect x="135" y="65" width="3" height="3" fill="yellow" />\n  <rect x="165" y="40" width="3" height="3" fill="yellow" />\n  <rect x="170" y="50" width="3" height="3" fill="yellow" />\n</svg>\n<|eot_id|>', 'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nGenerate a SVG code for the given input:\n\n### Input:\n \'Snow-capped mountains\',\n\n### Response:\n<svg viewBox="0 0 100 100" width="100" height="100" xmlns="http://www.w3.org/2000/svg">\n  <!-- Background -->\n  <rect x="0" y="0" width="100" height="100" fill="skyblue" />\n  \n  <!-- Mountains -->\n  <polygon points="20,80 50,30 80,80" fill="gray" stroke="black" stroke-width="1" />\n  <polygon points="10,80 40,40 70,80" fill="darkgray" stroke="black" stroke-width="1" />\n  \n  <!-- Snow Caps -->\n  <polygon points="45,40 50,30 55,40" fill="white" />\n  <polygon points="35,50 40,40 45,50" fill="white" />\n</svg>\n<|eot_id|>', 'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nGenerate a SVG code for the given input:\n\n### Input:\n \'Serene river flowing\',\n\n### Response:\n<svg viewBox="0 0 200 100" width="200" height="100" xmlns="http://www.w3.org/2000/svg">\n  <defs>\n    <linearGradient id="riverGradient" x1="0" y1="0" x2="0" y2="1">\n      <stop offset="0%" stop-color="#a0c4ff" />\n      <stop offset="100%" stop-color="#0077b6" />\n    </linearGradient>\n  </defs>\n  <rect x="0" y="0" width="200" height="100" fill="#caf0f8" />\n  <path d="M0,60 Q50,40 100,60 T200,60" fill="none" stroke="url(#riverGradient)" stroke-width="10" />\n</svg>\n<|eot_id|>', 'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nGenerate a SVG code for the given input:\n\n### Input:\n \'Golden desert dunes\',\n\n### Response:\n<svg viewBox="0 0 200 100" width="200" height="100" xmlns="http://www.w3.org/2000/svg">\n  <defs>\n    <linearGradient id="sandGradient" x1="0" y1="0" x2="0" y2="1">\n      <stop offset="0%" stop-color="#f4e7c3" />\n      <stop offset="100%" stop-color="#d2b48c" />\n    </linearGradient>\n  </defs>\n  <rect width="200" height="100" fill="url(#sandGradient)" />\n  <path d="M0 60 Q 50 40, 100 60 T 200 60 L 200 100 L 0 100 Z" fill="#e3c27b" />\n  <path d="M0 80 Q 50 60, 100 80 T 200 80 L 200 100 L 0 100 Z" fill="#d2b48c" opacity="0.8" />\n</svg>\n<|eot_id|>', 'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nGenerate a SVG code for the given input:\n\n### Input:\n \'Reflections on a lake\',\n\n### Response:\n<svg viewBox="0 0 200 200" width="200" height="200" xmlns="http://www.w3.org/2000/svg">\n  <defs>\n    <linearGradient id="skyGradient" x1="0" y1="0" x2="0" y2="1">\n      <stop offset="0%" stop-color="#87CEEB" />\n      <stop offset="100%" stop-color="#B0E0E6" />\n    </linearGradient>\n    <linearGradient id="waterGradient" x1="0" y1="0" x2="0" y2="1">\n      <stop offset="0%" stop-color="#4682B4" />\n      <stop offset="100%" stop-color="#5F9EA0" />\n    </linearGradient>\n  </defs>\n  <!-- Sky -->\n  <rect x="0" y="0" width="200" height="100" fill="url(#skyGradient)" />\n  <!-- Water -->\n  <rect x="0" y="100" width="200" height="100" fill="url(#waterGradient)" />\n  <!-- Sun -->\n  <circle cx="150" cy="50" r="20" fill="#FFD700" />\n  <!-- Reflection of the Sun -->\n  <ellipse cx="150" cy="150" rx="20" ry="5" fill="#FFD700" opacity="0.5" />\n  <!-- Mountains -->\n  <polygon points="0,100 50,30 100,100" 

In [8]:
# Check dataset sample output
dataset_train['text'][0]

'Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\nGenerate a SVG code for the given input:\n\n### Input:\n\'Golden wheat fields under a setting sun\',\n\n### Response:\n<svg viewBox="0 0 200 200" width="200" height="200" xmlns="http://www.w3.org/2000/svg">\n  <!-- Background for the sky -->\n  <rect x="0" y="0" width="200" height="100" fill="orange" opacity="0.7"/>\n  \n  <!-- Sun -->\n  <circle cx="100" cy="50" r="30" fill="yellow" opacity="0.8"/>\n  \n  <!-- Wheat fields -->\n  <rect x="0" y="100" width="200" height="100" fill="goldenrod"/>\n  \n  <!-- Wheat stalks -->\n  <g stroke="saddlebrown" stroke-width="2">\n    <line x1="30" y1="100" x2="30" y2="150"/>\n    <line x1="50" y1="100" x2="50" y2="150"/>\n    <line x1="70" y1="100" x2="70" y2="150"/>\n    <line x1="90" y1="100" x2="90" y2="150"/>\n    <line x1="110" y1="100" x2="110" y2="150"/>\n    <line x1="130" y1="100" x2="130" y2="150"/>\n    <line x1="150" y1="100" x2="150" y2="150"/>\n    <line x1="170" y1="100" x2="170" y2="150"/>\n  </g>\n  \n  <!-- Wheat heads -->\n  <g fill="gold" stroke="saddlebrown" stroke-width="0.5">\n    <ellipse cx="30" cy="95" rx="5" ry="10"/>\n    <ellipse cx="50" cy="95" rx="5" ry="10"/>\n    <ellipse cx="70" cy="95" rx="5" ry="10"/>\n    <ellipse cx="90" cy="95" rx="5" ry="10"/>\n    <ellipse cx="110" cy="95" rx="5" ry="10"/>\n    <ellipse cx="130" cy="95" rx="5" ry="10"/>\n    <ellipse cx="150" cy="95" rx="5" ry="10"/>\n    <ellipse cx="170" cy="95" rx="5" ry="10"/>\n  </g>\n</svg>\n<|eot_id|>'

In [9]:
import mlflow
mlflow.set_tracking_uri("ml_unsloth_runs")  # Or your remote tracking URI
mlflow.set_experiment("unsloth-lora-experiments")  # Your experiment name

<Experiment: artifact_location='/home/ml_unsloth_runs/990149045631854310', creation_time=1745245436792, experiment_id='990149045631854310', last_update_time=1745245436792, lifecycle_stage='active', name='unsloth-lora-experiments', tags={}>

In [10]:
from trl import SFTTrainer
from transformers import TrainingArguments
from unsloth import is_bfloat16_supported

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset_train,
    eval_dataset = dataset_test,  # Add test dataset here
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    packing = False, # Can make training 5x faster for short sequences.
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        num_train_epochs = 5, 
        max_steps = max_iter_steps,
        learning_rate = 5e-4,
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        logging_steps = 5,
        optim = "adamw_8bit", # "adamw_torch" better for fp16
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 123,
        eval_strategy = "steps", 
        eval_steps = 10, 
        output_dir = "outputs",
        report_to = "mlflow", # Use this for WandB etc
    ),
)

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/1975 [00:00<?, ? examples/s]

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/75 [00:00<?, ? examples/s]

In [11]:
formatted_model = base_model.replace(".", "").replace("-", "_")
run_name=formatted_model+train_parameters
with mlflow.start_run(run_name=run_name):
    trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 1,975 | Num Epochs = 3 | Total steps = 500
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 389,021,696/3,601,771,520 (10.80% trained)

Unsloth: Will smartly offload gradients to save VRAM!

Unsloth: Not an error, but LlamaForCausalLM does not accept `num_items_in_batch`.
Using gradient accumulation will be very slightly less accurate.
Read more on gradient accumulation issues here: https://unsloth.ai/blog/gradient

In [12]:
# #This ONLY saves the LoRA adapters, and not the full model.
# model.save_pretrained("./lora/lora_model_3b_v3") # Local saving
# tokenizer.save_pretrained("./lora/lora_model_3b_v3")

In [13]:
# import gc
# del model
# gc.collect()
# torch.cuda.empty_cache()

In [14]:
# import psutil

# def kill_large_python_processes():
#     # Loop over all running processes
#     for proc in psutil.process_iter(['pid', 'name', 'memory_info', 'exe']):
#         try:
#             # Check if the process is Python and type is 'C' (for computation)
#             if 'python' in proc.info['name'].lower():
#                 # Check if memory usage is greater than 2048 MB
#                 memory_usage_mb = proc.info['memory_info'].rss / (1024 * 1024)  # Convert bytes to MB
#                 if memory_usage_mb > 2048:
#                     print(f"Killing Python process with PID {proc.info['pid']} using {memory_usage_mb} MB memory")
#                     proc.kill()  # Kill the process
#         except (psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
#             pass  # Handle processes that might disappear during iteration

# #kill_large_python_processes()

In [15]:
# from unsloth import FastLanguageModel
# model, tokenizer = FastLanguageModel.from_pretrained(
# model_name = "./lora/lora_model_3b_v2", # YOUR MODEL YOU USED FOR TRAINING
# max_seq_length = 2048,
# dtype = (None),
# load_in_4bit = False,
# )
# FastLanguageModel.for_inference(model) # Enable native 2x faster inference

In [16]:
# # alpaca_prompt = You MUST copy from above!
# alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

# ### Instruction:
# {}

# ### Input:
# {}

# ### Response:
# {}"""

# inputs = tokenizer(
# [
#     alpaca_prompt.format(
#         "Please write a SVG code fo rthe given topic?", # instruction
#         "Golden sun rising in the east", # input
#         "", # output - leave this blank for generation!
#     )
# ], return_tensors = "pt").to("cuda")

# outputs = model.generate(**inputs, max_new_tokens = 1024, use_cache = True)
# tokenizer.batch_decode(outputs)

In [17]:
#save merged 16bit
import os
dir_path = "./lora/"+run_name
os.makedirs(dir_path, exist_ok=True)
model.save_pretrained_merged(dir_path, tokenizer, save_method = "merged_16bit")

Unsloth: Merging 4bit and LoRA weights to 16bit...
Unsloth: Will use up to 12.16 out of 31.21 RAM for saving.
Unsloth: Saving model... This might take 5 minutes ...

 57%|████████████████████████████████████████████████████████████████████████████████████                                                               | 16/28 [00:00<00:00, 77.43it/s]
We will save to Disk and not RAM now.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [00:01<00:00, 14.27it/s]

Unsloth: Saving tokenizer... Done.
Done.